
ALTER TABLE FORMULARIO_ADMINISTRATIVO
add ID_FORMULARIO NUMERIC (30) NOT NULL;

ALTER TABLE FORMULARIO_ADMINISTRATIVO ADD (
CONSTRAINT PK_ID_FORMULARIO PRIMARY KEY (ID_FORMULARIO));

CREATE SEQUENCE SEQ_ID_FORMULARIO START WITH 1;

CREATE OR REPLACE TRIGGER TRIG_ID_FORMULARIO
    BEFORE INSERT ON FORMULARIO_ADMINISTRATIVO
    FOR EACH ROW
BEGIN
  SELECT SEQ_ID_FORMULARIO.NEXTVAL
  INTO   :new.ID_FORMULARIO
  FROM   dual;
END;


INSERT INTO FORMULARIO_ADMINISTRATIVO (nombre,apellido,tipo_evento,contacto,direccion,email,fecha,hora) 
VALUES ('prueba2','prueba2','prueba','prueba','prueba','prueba@gmail.com','20/04/24','20:15');
