SELECT * FROM archivo_bfile_cotizador
ORDER BY FECHA DESC;

INSERT INTO archivo_bfile_cotizador (nombre,fecha,hora,archivo)
VALUES ('PRUEBA_TEST_5','28/02/24','14:15', BFILENAME('DIR_ARCHIVO_COTIZADOR', 'Cot2024_28.txt'));

SELECT * FROM SIGNUP WHERE HORA IS NOT NULL 
ORDER BY ID_SIGNUP DESC;

SELECT * FROM LOGIN 
ORDER BY ID_LOGIN DESC;

SELECT * FROM FORMULARIO_ADMINISTRATIVO 
where hora is not null
order by fecha desc;

SELECT * FROM PAGO_COTIZACION;

ALTER TABLE PAGO_COTIZACION 
ADD ID_PAGO_COTIZACION NUMBER (30) NOT NULL;

DELETE FROM PAGO_COTIZACION;

ALTER TABLE PAGO_COTIZACION ADD (
CONSTRAINT PK_PAGO_COTIZACION PRIMARY KEY (ID_PAGO_COTIZACION));

CREATE SEQUENCE SEQ_ID_PAGO_COTIZACION START WITH 1; --PLSQL 

CREATE OR REPLACE TRIGGER TRIG_ID_PAGO_COTIZACION  --PLSQL
    BEFORE INSERT ON PAGO_COTIZACION 
    FOR EACH ROW
BEGIN
  SELECT SEQ_ID_PAGO_COTIZACION.NEXTVAL
  INTO   :new.ID_PAGO_COTIZACION
  FROM   dual;
END;

INSERT INTO PAGO_COTIZACION(RUT,NUMERO_CUENTA,NOMBRE_TITULAR,CVC_TITULAR,FECHA,HORA)
VALUES (202814085,'4345 3677 8090','JAIME','309','26/02/24','14:56');

---------------------------------------------------
SELECT * FROM REGISTRO_COTIZACION;

ALTER TABLE REGISTRO_COTIZACION
add ID_REGISTRO_COTIZACION NUMERIC (30) NOT NULL;

--DELETE FROM REGISTRO_COTIZACION;

ALTER TABLE REGISTRO_COTIZACION ADD (
CONSTRAINT PK_REGISTRO_COTIZACION PRIMARY KEY (ID_REGISTRO_COTIZACION));

CREATE SEQUENCE SEQ_ID_REGISTRO_COTIZACION START WITH 1;

CREATE OR REPLACE TRIGGER TRIG_ID_REGISTRO_COTIZACION  --PLSQL
    BEFORE INSERT ON REGISTRO_COTIZACION
    FOR EACH ROW
BEGIN
  SELECT SEQ_ID_REGISTRO_COTIZACION.NEXTVAL
  INTO   :new.ID_REGISTRO_COTIZACION
  FROM   dual;
END;

INSERT INTO REGISTRO_COTIZACION (RUT,NOMBRE_TITULAR,APELLIDO_TITULAR,EMAIL_TITULAR,METODO_PAGO,FECHA,HORA,NOMBRE_BANCO_TARJETA)
VALUES (202814085,'JAIME','MENDOZA','JAIMERETAMAL47@GMAIL.COM','DEBITO','26/02/24','13:36','BANCO ESTADO');
--DELETE FROM archivo_bfile_cotizador;

SELECT * FROM REGISTRO_COTIZACION;
----------------------------------------
ALTER TABLE ARCHIVO_BFILE_COTIZADOR
drop COLUMN ARCHIVO;

ALTER TABLE ARCHIVO_BFILE_COTIZADOR
ADD ARCHIVO BFILE;


 INSERT INTO ARCHIVO_BFILE_COTIZADOR (nombre,fecha,hora,archivo) 
 VALUES ('PRUEBA_TEST_1','24/02/24','15:24','COTIZACION_BRUNO_FRITZH_23_02_24.xlsx');