CREATE TABLE LOGIN (
 CORREO VARCHAR(100) PRIMARY KEY, 
 CONTRASEÑA VARCHAR(100) NOT NULL,
 NOMBRE VARCHAR(100)
);

INSERT INTO LOGIN VALUES ('JAIMERETAMAL47@GMAIL.COM','NUEVA2024','JAIME');

INSERT INTO SIGNUP VALUES ('JAIME','JAIMERETAMAL47@GMAIL.COM','NUEVA2024');
--ALTER TABLE LOGIN  add constraint FK_SIGNUP FOREIGN KEY (NOMBRE) REFERENCES SIGNUP(NOMBRE);
--ALTER TABLE LOGIN 
--DROP CONSTRAINT FK_SIGNUP;


--DROP TABLE LOGIN;
--DROP TABLE SIGNUP;

SELECT * FROM LOGIN;
SELECT * FROM SIGNUP;

CREATE TABLE SIGNUP (
 NOMBRE VARCHAR(100) PRIMARY KEY,
 CORREO VARCHAR(100),
 FOREIGN KEY (CORREO) REFERENCES LOGIN(CORREO) , 
 CONTRASEÑA_NUEVA VARCHAR(100)
);