

--CONSULTA DE BD JOIN DE LOGIN Y SIGNUP
SELECT  L.ID_LOGIN ,L.EMAIL  ,S.LOGIN_ID AS LOGIN_SIGNUP,
S.EMAIL AS EMAIL_SIGNUP
FROM LOGIN L
FULL JOIN SIGNUP S 
ON l.ID_LOGIN=S.LOGIN_ID
WHERE L.ID_LOGIN=S.LOGIN_ID;

