create or replace NONEDITIONABLE PROCEDURE INSERTAR_REGISTRO_FORMULARIO_ADMINISTRATIVO (NOMBRE_REGISTRO_FORMULARIO   FORMULARIO_ADMINISTRATIVO.NOMBRE%TYPE,
APELLIDO_REGISTRO_FORMULARIO   FORMULARIO_ADMINISTRATIVO.APELLIDO%TYPE, 
TIPO_EVENTO_REGISTRO_FORMULARIO  FORMULARIO_ADMINISTRATIVO.CONTACTO%TYPE,
CONTACTO_REGISTRO_FORMULARIO  FORMULARIO_ADMINISTRATIVO.TIPO_EVENTO%TYPE,
DIRECCION_REGISTRO_FORMULARIO  FORMULARIO_ADMINISTRATIVO.DIRECCION%TYPE,
EMAIL_REGISTRO_FORMULARIO  FORMULARIO_ADMINISTRATIVO.EMAIL%TYPE,
SIGNUP_ID_REGISTRO   FORMULARIO_ADMINISTRATIVO.SIGNUP_ID%TYPE,
FECHA_FORMULARIO_ADMINISTRATIVO_REGISTRO FORMULARIO_ADMINISTRATIVO.FECHA%TYPE)
AS
--CURSOR INSERTAR REGISTRO FORMULARIO_ADMINISTRATIVO
 CURSOR C_INSERTAR 
 IS SELECT * FROM FORMULARIO_ADMINISTRATIVO
 WHERE NOMBRE=NOMBRE_REGISTRO_FORMULARIO
 AND APELLIDO=APELLIDO_REGISTRO_FORMULARIO
 AND TIPO_EVENTO=TIPO_EVENTO_REGISTRO_FORMULARIO
 AND CONTACTO=CONTACTO_REGISTRO_FORMULARIO
 AND DIRECCION=DIRECCION_REGISTRO_FORMULARIO
 AND EMAIL=EMAIL_REGISTRO_FORMULARIO
 AND SIGNUP_ID=SIGNUP_ID_REGISTRO
 AND FECHA=FECHA_FORMULARIO_ADMINISTRATIVO_REGISTRO;

 CUR_INSERT C_INSERTAR%ROWTYPE;

BEGIN
  OPEN C_INSERTAR;
  FETCH C_INSERTAR INTO CUR_INSERT;
  INSERT INTO FORMULARIO_ADMINISTRATIVO VALUES (NOMBRE_REGISTRO_FORMULARIO,APELLIDO_REGISTRO_FORMULARIO,TIPO_EVENTO_REGISTRO_FORMULARIO,
  CONTACTO_REGISTRO_FORMULARIO,DIRECCION_REGISTRO_FORMULARIO,EMAIL_REGISTRO_FORMULARIO,SIGNUP_ID_REGISTRO,FECHA_FORMULARIO_ADMINISTRATIVO_REGISTRO);
  CLOSE C_INSERTAR;
  --
  COMMIT;
END;

/*ALTER TABLE FORMULARIO_ADMINISTRATIVO
ADD FECHA VARCHAR(100) DEFAULT '18-01-2024';*/

--drop procedure INSERTAR_REGISTRO_FORMULARIO_ADMINISTRATIVO;