create or replace NONEDITIONABLE PROCEDURE BORRAR_REGISTRO_LOGIN(ID_LOGIN_REGISTRO LOGIN.ID_LOGIN%TYPE)
AS

 CURSOR C_BORRAR_LOGIN
 IS SELECT * FROM LOGIN
 WHERE ID_LOGIN=ID_LOGIN_REGISTRO;

 CUR_BORRAR_REGISTRO  C_BORRAR_LOGIN%ROWTYPE;

BEGIN
    OPEN C_BORRAR_LOGIN;
    FETCH C_BORRAR_LOGIN INTO CUR_BORRAR_REGISTRO;
    DELETE 
    FROM LOGIN 
    WHERE ID_LOGIN=ID_LOGIN_REGISTRO;

    CLOSE C_BORRAR_LOGIN;
    COMMIT;
END;