create or replace NONEDITIONABLE PROCEDURE ACTUALIZAR_REGISTRO_LOGIN(ID_LOGIN_REGISTRO LOGIN.ID_LOGIN%TYPE,
EMAIL_REGISTRO LOGIN.EMAIL%TYPE,
CLAVE_REGISTRO LOGIN.CLAVE%TYPE,
ID_SIGNUP_REGISTRO LOGIN.SIGNUP_ID%TYPE,
FECHA_LOGIN_REGISTRO LOGIN.FECHA%TYPE)
AS

 CURSOR C_ACTUALIZAR_LOGIN 
 IS SELECT * FROM LOGIN
 WHERE ID_LOGIN=ID_LOGIN_REGISTRO
 AND EMAIL=EMAIL_REGISTRO
 AND CLAVE=CLAVE_REGISTRO
 AND FECHA=FECHA_LOGIN_REGISTRO;

 CUR_ACTUALIZAR_LOGIN C_ACTUALIZAR_LOGIN%ROWTYPE;

BEGIN

 OPEN C_ACTUALIZAR_LOGIN;
 FETCH C_ACTUALIZAR_LOGIN INTO CUR_ACTUALIZAR_LOGIN;

 UPDATE LOGIN 
 SET ID_LOGIN=ID_LOGIN_REGISTRO,
  EMAIL=EMAIL_REGISTRO,
  CLAVE=CLAVE_REGISTRO,
  FECHA=FECHA_LOGIN_REGISTRO
 WHERE ID_LOGIN=ID_LOGIN_REGISTRO;

 CLOSE C_ACTUALIZAR_LOGIN;
 COMMIT;
END;