SELECT * FROM LOGIN;

SELECT * FROM SIGNUP;

CREATE TABLE SIGNUP (
   ID_SIGNUP NUMBER(10) PRIMARY KEY,
   EMAIL VARCHAR(100) NOT NULL,
   CLAVE_NUEVA VARCHAR(100) NOT NULL,
   CLAVE VARCHAR(100) NOT NULL
);

ALTER TABLE SIGNUP ADD NOMBRE VARCHAR(100) DEFAULT 0 NOT NULL;
ALTER TABLE SIGNUP ADD APELLIDO VARCHAR(100) DEFAULT 0 NOT NULL;

SELECT * FROM SIGNUP;

CREATE TABLE LOGIN (
    ID_LOGIN NUMBER(10) PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    CLAVE VARCHAR(100) NOT NULL,
    SIGNUP_ID NUMBER(10) NOT NULL
);

/*ALTER TABLE SIGNUP 
ADD CONSTRAINT FORMULARIO_ADMINISTRATIVO_NOMBRE_SIGNUP_FK
FOREIGN KEY (SIGNUP_ID) REFERENCES FORMULARIO_ADMINISTRATIVO (NOMBRE);*/
DROP PROCEDURE BORRAR_REGISTRO_SIGNUP;

SELECT * FROM SIGNUP;



--CREAR TABLA DE FORMULARIO ADMINISTRATIVO 

CREATE TABLE FORMULARIO_ADMINISTRATIVO (
  NOMBRE VARCHAR(100) PRIMARY KEY,
  APELLIDO VARCHAR(100) NOT NULL, 
  TIPO_EVENTO VARCHAR(100) NOT NULL,
  CONTACTO VARCHAR(100) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL ,
  EMAIL VARCHAR(100) NOT NULL
);