
-----
CREATE TABLE PAGO_COTIZACION (
    RUT NUMBER(30) NOT NULL,
    NUMERO_CUENTA VARCHAR(100) NOT NULL,
    NOMBRE_TITULAR VARCHAR(100) NOT NULL,
    CVC_TITULAR VARCHAR(10) NOT NULL,
    FECHA VARCHAR(100) NOT NULL,
    HORA VARCHAR(100) NOT NULL
)
----
CREATE TABLE REGISTRO_COTIZACION (
    RUT NUMBER(30) NOT NULL,
    NOMBRE_TITULAR VARCHAR(100) NOT NULL,
    APELLIDO_TITULAR VARCHAR(100) NOT NULL,
    EMAIL_TITULAR VARCHAR(100) NOT NULL,
    METODO_PAGO VARCHAR(100) NOT NULL,
    FECHA  VARCHAR(100) NOT NULL,
    HORA VARCHAR(100) NOT NULL
)

---
SELECT * FROM PAGO_COTIZACION;
----
INSERT INTO PAGO_COTIZACION (RUT,NUMERO_CUENTA,NOMBRE_TITULAR,CVC_TITULAR,FECHA,HORA)
VALUES (202814085,'4120032000881144','JAIME NICOLAS RETAMAL MENDOZA','905','23/02/24','17:03');
-----
SELECT * FROM REGISTRO_COTIZACION;
---
INSERT INTO REGISTRO_COTIZACION (RUT,NOMBRE_TITULAR,APELLIDO_TITULAR,EMAIL_TITULAR,METODO_PAGO,FECHA,HORA,NOMBRE_BANCO_TARJETA)
VALUES (202814085,'JAIME NICOLAS','RETAMAL MENDOZA','JAIMERETAMAL47@GMAIL.COM','CREDITO','23/02/24','17:56','BANCO ESTADO');

ALTER TABLE REGISTRO_COTIZACION
ADD NOMBRE_BANCO_TARJETA VARCHAR(100) NOT NULL;

DELETE FROM REGISTRO_COTIZACION;
------