create or replace NONEDITIONABLE PROCEDURE BORRAR_REGISTRO_SIGNUP(ID_SIGNUP_REGISTRO SIGNUP.ID_SIGNUP%TYPE)
AS

 CURSOR C_BORRAR_SIGNUP 
 IS SELECT * FROM SIGNUP
 WHERE ID_SIGNUP=ID_SIGNUP_REGISTRO;

 CUR_BORRAR_REGISTRO  C_BORRAR_SIGNUP%ROWTYPE;

BEGIN
    OPEN C_BORRAR_SIGNUP;
    FETCH C_BORRAR_SIGNUP INTO CUR_BORRAR_REGISTRO;
    DELETE 
    FROM SIGNUP 
    WHERE ID_SIGNUP=ID_SIGNUP_REGISTRO;

    CLOSE C_BORRAR_SIGNUP;
    COMMIT;
END;