/* * from ARCHIVO_BLOB_COTIZADOR;

ALTER TABLE ARCHIVO_BLOB_COTIZADOR
ADD NOMBRE_BLOB_REGISTRO VARCHAR(100);*/

--SELECT * FROM ARCHIVO_BFILE_COTIZADOR;

--DELETE FROM ARCHIVO_BFILE_COTIZADOR WHERE ID_COTIZADOR=50;

CREATE OR REPLACE PROCEDURE CARGA_ARCHIVO_BFILE_COTIZADOR(ID_ARCHIVO_REGISTRO  ARCHIVO_BFILE_COTIZADOR.ID_COTIZADOR%TYPE,
DESCRIPCION_BFILE ARCHIVO_BFILE_COTIZADOR.NOMBRE%TYPE,
NOMBRE_BFILE  ARCHIVO_BFILE_COTIZADOR.NOMBRE%TYPE)
AS

   -- V_TEMP BLOB;
   -- V_BFILE BFILE;
   -- V_NOMBRE_FOTO VARCHAR(100);
    
BEGIN
    
   
    IF ID_ARCHIVO_REGISTRO IS NOT NULL THEN
    
    INSERT INTO archivo_bfile_cotizador VALUES (ID_ARCHIVO_REGISTRO, DESCRIPCION_BFILE, bfilename('DIR_ARCHIVO_RUTA_8',NOMBRE_BFILE));
    
    END IF;
    
    COMMIT;
    

END;



--drop procedure CARGA_ARCHIVO_BFILE_COTIZADOR;

--EXECUTE CARGA_ARCHIVO_BFILE_COTIZADOR (75,'CONEXION ORACLE','coneccionORCL.txt');