create or replace NONEDITIONABLE FUNCTION VALIDACION_LOGIN_CLAVE (V_CLAVE VARCHAR)  
 RETURN VARCHAR
IS

 V_VALIDACION VARCHAR(100);


BEGIN 

  SELECT CLAVE INTO V_VALIDACION
  FROM LOGIN
  WHERE CLAVE=V_CLAVE;
  RETURN V_VALIDACION;

  --V_EMAIL := SIGNUP.EMAIL;

  IF V_CLAVE IS NOT NULL
  THEN 
   RETURN 'OK';
  ELSE
   RETURN 'NO OK';
  END IF;

EXCEPTION
    WHEN no_data_found then return 0;

END;