create or replace NONEDITIONABLE PROCEDURE ACTUALIZAR_REGISTRO_SIGNUP (ID_SIGNUP_REGISTRO SIGNUP.ID_SIGNUP%TYPE,
EMAIL_SIGNUP_REGISTRO SIGNUP.EMAIL%TYPE, 
CLAVE_NUEVA_SIGNUP_REGISTRO SIGNUP.CLAVE_NUEVA%TYPE,
CLAVE_SIGNUP_REGISTRO SIGNUP.CLAVE%TYPE,
NOMBRE_SIGNUP_REGISTRO SIGNUP.NOMBRE%TYPE,
APELLIDO_SIGNUP_REGISTRO SIGNUP.APELLIDO%TYPE,
FECHA_SIGNUP_REGISTRO SIGNUP.FECHA%TYPE)
AS

 CURSOR C_ACTUALIZAR_SIGNUP 
 IS SELECT * FROM SIGNUP
 WHERE ID_SIGNUP=ID_SIGNUP_REGISTRO
 AND EMAIL=EMAIL_SIGNUP_REGISTRO
 AND CLAVE_NUEVA=CLAVE_NUEVA_SIGNUP_REGISTRO
 AND CLAVE=CLAVE_SIGNUP_REGISTRO
 AND NOMBRE=NOMBRE_SIGNUP_REGISTRO
 AND APELLIDO=APELLIDO_SIGNUP_REGISTRO
 AND FECHA=FECHA_SIGNUP_REGISTRO;

 CUR_ACTUALIZAR_SIGNUP C_ACTUALIZAR_SIGNUP%ROWTYPE;

BEGIN

 OPEN C_ACTUALIZAR_SIGNUP;
 FETCH C_ACTUALIZAR_SIGNUP INTO CUR_ACTUALIZAR_SIGNUP;

 UPDATE SIGNUP 
 SET ID_SIGNUP=ID_SIGNUP_REGISTRO,
    EMAIL=EMAIL_SIGNUP_REGISTRO,
    CLAVE_NUEVA=CLAVE_NUEVA_SIGNUP_REGISTRO,
    CLAVE=CLAVE_SIGNUP_REGISTRO,
    NOMBRE=NOMBRE_SIGNUP_REGISTRO,
    APELLIDO=APELLIDO_SIGNUP_REGISTRO,
    FECHA=FECHA_SIGNUP_REGISTRO
 WHERE ID_SIGNUP=ID_SIGNUP_REGISTRO;

 CLOSE C_ACTUALIZAR_SIGNUP;
 COMMIT;
END;