create or replace NONEDITIONABLE PROCEDURE BORRAR_REGISTRO_FORMULARIO_ADMINISTRATIVO (
NOMBRE_REGISTRO  FORMULARIO_ADMINISTRATIVO.NOMBRE%TYPE,
SIGNUP_ID_REGISTRO   FORMULARIO_ADMINISTRATIVO.SIGNUP_ID%TYPE)
AS
--CURSOR INSERTAR REGISTRO FORMULARIO_ADMINISTRATIVO
 CURSOR C_INSERTAR 
 IS SELECT * FROM FORMULARIO_ADMINISTRATIVO
 WHERE NOMBRE=NOMBRE_REGISTRO 
 AND SIGNUP_ID=SIGNUP_ID_REGISTRO;

 CUR_INSERT C_INSERTAR%ROWTYPE;

BEGIN
  OPEN C_INSERTAR;
  FETCH C_INSERTAR INTO CUR_INSERT;
  DELETE FROM FORMULARIO_ADMINISTRATIVO WHERE NOMBRE=NOMBRE_REGISTRO
  AND SIGNUP_ID=SIGNUP_ID_REGISTRO;
  CLOSE C_INSERTAR;
  --
  COMMIT;
END;

--EXECUTE BORRAR_REGISTRO_FORMULARIO_ADMINISTRATIVO('JAIME',1);

--SELECT * FROM formulario_administrativo;

--DROP PROCEDURE BORRAR_REGISTRO_FORMULARIO_ADMINISTRATIVO;