create or replace NONEDITIONABLE FUNCTION VALIDACION_LOGIN_EMAIL (V_EMAIL  VARCHAR)  
 RETURN VARCHAR
IS

 V_VALIDACION VARCHAR(100);


BEGIN 

  SELECT EMAIL INTO V_VALIDACION
  FROM LOGIN
  WHERE EMAIL=V_EMAIL;
  RETURN V_VALIDACION;

  --V_EMAIL := SIGNUP.EMAIL;

  IF V_EMAIL IS NOT NULL
  THEN 
   RETURN 'OK';
  ELSE
   RETURN 'NO OK';
  END IF;

EXCEPTION
    WHEN no_data_found then return 0;

END;