create or replace NONEDITIONABLE PROCEDURE INSERTAR_REGISTRO_LOGIN (ID_LOGIN_REGISTRO LOGIN.ID_LOGIN%TYPE,
EMAIL_REGISTRO LOGIN.EMAIL%TYPE,
CLAVE_REGISTRO LOGIN.CLAVE%TYPE,
SIGNUP_REGISTRO_ID   LOGIN.SIGNUP_ID%TYPE,
FECHA_LOGIN_REGISTRO LOGIN.FECHA%TYPE)
AS

 CURSOR C_INSERTAR_LOGIN 
 IS SELECT * FROM LOGIN
 WHERE ID_LOGIN=ID_LOGIN_REGISTRO
 AND EMAIL=EMAIL_REGISTRO
 AND CLAVE=CLAVE_REGISTRO
 AND SIGNUP_ID=SIGNUP_REGISTRO_ID
 AND FECHA=FECHA_LOGIN_REGISTRO;

 CUR_INSERT_LOGIN C_INSERTAR_LOGIN%ROWTYPE;

BEGIN

 OPEN C_INSERTAR_LOGIN;
 FETCH C_INSERTAR_LOGIN INTO CUR_INSERT_LOGIN;
 INSERT INTO LOGIN VALUES (ID_LOGIN_REGISTRO,EMAIL_REGISTRO,CLAVE_REGISTRO,SIGNUP_REGISTRO_ID,FECHA_LOGIN_REGISTRO);

 CLOSE C_INSERTAR_LOGIN;
 COMMIT;
END;