--SELECT * FROM LOGIN;
--SELECT * FROM SIGNUP;

---DROP TABLE LOGIN;
---DROP TABLE SIGNUP;

CREATE TABLE SIGNUP (
   ID_SIGNUP NUMBER(10) PRIMARY KEY,
   EMAIL VARCHAR(100) NOT NULL,
   CLAVE_NUEVA VARCHAR(100) NOT NULL,
   CLAVE VARCHAR(100) NOT NULL
);

CREATE TABLE LOGIN (
    ID_LOGIN NUMBER(10) PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    CLAVE VARCHAR(100) NOT NULL,
    SIGNUP_ID NUMBER(10) NOT NULL
);

SELECT * FROM FORMULARIO_ADMINISTRATIVO;

EXECUTE INSERTAR_REGISTRO_FORMULARIO_ADMINISTRATIVO('JUAN','MENDOZA','AUTOMOTORA','228496895','JOAQUIN PALACIOS 556','JUAN2024@GMAIL.COM');

/*ALTER TABLE LOGIN 
ADD CONSTRAINT LOGIN_ID_SIGNUP_FK
FOREIGN KEY (SIGNUP_ID) REFERENCES SIGNUP (ID_SIGNUP);*/

/*INSERT INTO SIGNUP VALUES (1,'JAIME2024@GMAIL.COM','JAIME2024','JAIME2024');
INSERT INTO SIGNUP VALUES (2,'NICOLAS2024@GMAIL.COM','NICOLAS2024','NICOLAS2024');
INSERT INTO SIGNUP VALUES (3,'MENDOZA2024@GMAIL.COM','MENDOZA2024','MENDOZA2024');*/

--DELETE FROM SIGNUP;


--DROP PROCEDURE INSERTAR_REGISTRO_SIGNUP;

Jaime2024


