create or replace NONEDITIONABLE PROCEDURE REGISTRO_INSERT_FACTURA_ENVIO_EMAIL (

ID_REGISTRO NUMBER,
NOMBRE_COMPLETO factura_registro.nombre_completo%TYPE,
APELLIDO_COMPLETO factura_registro.apellido_completo%TYPE,
NOMBRE_USUARIO factura_registro.nombre_usuario%TYPE,
EMAIL factura_registro.email%TYPE,
DIRECCION factura_registro.direccion%TYPE,
TELEFONO factura_registro.telefono%TYPE,
PAIS factura_registro.pais%TYPE,
ESTADO factura_registro.estado%TYPE,
CODIGO_POSTAL factura_registro.codigo_postal%TYPE,
ID_COMPRA number,
CARRO_COTIZACION factura_registro.carro_cotizacion%TYPE,
DESCRIPCION_COTIZACION factura_registro.descripcion_cotizacion%TYPE,
ID_COMPRA_TARJETA number,
TIPO_TARJETA factura_registro.tipo_tarjeta%TYPE,
NOMBRE_TARJETA factura_registro.nombre_tarjeta%TYPE,
NUMERO_TARJETA factura_registro.numero_tarjeta%TYPE,
EXPIRACION number,
CVV factura_registro.cvv%TYPE)

--archivo_bfile_cotizador.archivo%TYPE)
AS


--VARIABLE EMAIL
from_user varchar2(50):='user_boss';
from_sndr varchar2(50):='jaimeretamal47@gmail.com';
rcpt_to varchar2(2000):='jaimeretamal47@gmail.com';
msubj varchar2(80):='PRUEBA DE PLSQL EMAIL';
mmsg varchar2(400):= 'ESTA ES UNA PRUEBA DE PLSQL EMAIL...';
ret_msg varchar2(400);


 CURSOR C_INSERTAR_FACTURA
 IS SELECT * FROM FACTURA_REGISTRO
 WHERE NOMBRE_COMPLETO=NOMBRE_COMPLETO;

 CUR_INSERT_FACTURA  C_INSERTAR_FACTURA%ROWTYPE;

 --VARIABLE DIRECTORIO
 --ARCHIVO_C VARCHAR2(100) := 'cotizacion1306.txt';
 --RUTA_ARCHIVO_COTIZACION VARCHAR2(100) := 'C:\Users';

BEGIN

 IF EMAIL IS NOT NULL  THEN 

 OPEN C_INSERTAR_FACTURA;
 FETCH C_INSERTAR_FACTURA INTO CUR_INSERT_FACTURA;
 INSERT INTO FACTURA_REGISTRO
 VALUES (ID_REGISTRO,NOMBRE_COMPLETO,APELLIDO_COMPLETO,NOMBRE_USUARIO
 ,EMAIL,DIRECCION,TELEFONO,PAIS,ESTADO,CODIGO_POSTAL,ID_COMPRA,
 CARRO_COTIZACION,DESCRIPCION_COTIZACION,ID_COMPRA_TARJETA,TIPO_TARJETA,
 NOMBRE_TARJETA,NUMERO_TARJETA,EXPIRACION,CVV);

 CLOSE C_INSERTAR_FACTURA;

 ret_msg := USER_BOSS.send_email(from_user, from_sndr, rcpt_to, msubj, mmsg, 'COTIZACION.TXT');

 COMMIT;

 END IF;
END;

--SELECT * FROM factura_registro;

--EXECUTE REGISTRO_INSERT_FACTURA_ENVIO_EMAIL(1,'JAIME NICOLAS','RETAMAL MENDOZA','JAIME','JAIMERETAMAL47@GMAIL.COM','JOAQUIN PALACIOS 556','990383275','CHILE','SANTIAGO','1800000',1,'COTIZACION AUTOMOTRIZ','SISTEMA DE AUTOMOTRIZ BMW',1,'TARJETA DEBITO','JAIME NICOLAS RETAMAL MENDOZA','4445 6770 9089',2907,'318');