CREATE OR REPLACE 
PACKAGE PCK_VALIDACION_PROCESO_APP AS 

PROCEDURE VALIDACION_SEGURIDAD_INSERT_LOGIN(ID_REGISTRO NUMBER,EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,FECHA_LOGIN_REGISTRO VARCHAR2, HORA_LOGIN_REGISTRO VARCHAR2);

PROCEDURE VALIDACION_SEGURIDAD_INSERT_SIGNUP(EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,CLAVE VARCHAR,FECHA VARCHAR,NOMBRE VARCHAR,APELLIDO VARCHAR2,HORA_REGISTRO VARCHAR2);



  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PCK_VALIDACION_PROCESO_APP;