create or replace NONEDITIONABLE PROCEDURE VALIDACION_SEGURIDAD_INSERT_CRUD_ARCHIVO(
NOMBRE CRUD_ARCHIVO_COTIZACION.NOMBRE%TYPE,
EMAIL CRUD_ARCHIVO_COTIZACION.EMAIL%TYPE,
DIRECCION CRUD_ARCHIVO_COTIZACION.DIRECCION%TYPE,
SISTEMA_DESCRIPCION CRUD_ARCHIVO_COTIZACION.SISTEMA_DESCRIPCION%TYPE,
FECHA CRUD_ARCHIVO_COTIZACION.FECHA%TYPE,
ARCHIVO CRUD_ARCHIVO_COTIZACION.ARCHIVO_COTIZACION%TYPE,
ESTADO CRUD_ARCHIVO_COTIZACION.ESTADO%TYPE,
HORA CRUD_ARCHIVO_COTIZACION.HORA%TYPE)
AS

 
 CURSOR C_INSERTAR_CRUD
 IS SELECT * FROM CRUD_ARCHIVO_COTIZACION;

 CUR_INSERT__CRUD C_INSERTAR_CRUD%ROWTYPE;


BEGIN

    IF NOMBRE IS NOT NULL AND ARCHIVO = '.XLSX' || '.PDF' || '.CSV' THEN

     OPEN C_INSERTAR_CRUD;
     FETCH C_INSERTAR_CRUD INTO CUR_INSERT__CRUD;

     INSERT INTO CRUD_ARCHIVO_COTIZACION
     VALUES (NOMBRE,EMAIL,DIRECCION,SISTEMA_DESCRIPCION,FECHA,ARCHIVO,ESTADO,HORA);
     CLOSE C_INSERTAR_CRUD;
     COMMIT;

     ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');

        ROLLBACK;

    END IF;

END;