create or replace NONEDITIONABLE PROCEDURE VALIDACION_SEGURIDAD_INSERT_ARCHIVO(
NOMBRE_REGISTRO ARCHIVO_COTIZADOR.NOMBRE%TYPE,
FECHA_REGISTRO ARCHIVO_COTIZADOR.FECHA%TYPE,
HORA_REGISTRO ARCHIVO_COTIZADOR.HORA%TYPE,
ARCHIVO_REGISTRO ARCHIVO_COTIZADOR.ARCHIVO%TYPE)
AS

 
 CURSOR C_INSERTAR_ARCHIVO
 IS SELECT * FROM ARCHIVO_COTIZADOR;

 CUR_INSERT_ARCHIVO C_INSERTAR_ARCHIVO%ROWTYPE;


BEGIN

    IF NOMBRE_REGISTRO IS NOT NULL AND ARCHIVO_REGISTRO IS NOT NULL THEN

     OPEN C_INSERTAR_ARCHIVO;
     FETCH C_INSERTAR_ARCHIVO INTO CUR_INSERT_ARCHIVO;

     INSERT INTO ARCHIVO_COTIZADOR
     VALUES (NOMBRE_REGISTRO,FECHA_REGISTRO,HORA_REGISTRO,ARCHIVO_REGISTRO);
     CLOSE C_INSERTAR_ARCHIVO;
     COMMIT;

     ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');

        ROLLBACK;

    END IF;

END;