create or replace NONEDITIONABLE PACKAGE PCK_REGISTRO_LOGIN 
AS


--DECLARAMOS LOS PROCEDIMIENTOS EN EL PACKAGE
PROCEDURE REGISTRO_VALIDACION_INSERT_LOGIN(ID_REGISTRO NUMBER,EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,FECHA_LOGIN_REGISTRO VARCHAR2,HORA_LOGIN_REGISTRO VARCHAR2);

PROCEDURE ACTUALIZAR_REGISTRO_LOGIN(ID_LOGIN_REGISTRO NUMBER,EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,FECHA_LOGIN_REGISTRO VARCHAR2,HORA_LOGIN_REGISTRO VARCHAR2);



END PCK_REGISTRO_LOGIN;