create or replace NONEDITIONABLE PACKAGE BODY PCK_VALIDACION_ARCHIVO_COTIZACION_APP
AS


PROCEDURE VALIDACION_SEGURIDAD_INSERT_ARCHIVO(NOMBRE_REGISTRO VARCHAR2,FECHA_REGISTRO VARCHAR2, HORA_REGISTRO VARCHAR2,ARCHIVO_REGISTRO VARCHAR2)
AS

 
 CURSOR C_INSERTAR_ARCHIVO
 IS SELECT * FROM ARCHIVO_COTIZADOR;

 CUR_INSERT_ARCHIVO C_INSERTAR_ARCHIVO%ROWTYPE;


BEGIN

    IF NOMBRE_REGISTRO IS NOT NULL AND ARCHIVO_REGISTRO IS NOT NULL THEN

     OPEN C_INSERTAR_ARCHIVO;
     FETCH C_INSERTAR_ARCHIVO INTO CUR_INSERT_ARCHIVO;

     INSERT INTO ARCHIVO_COTIZADOR
     VALUES (NOMBRE_REGISTRO,FECHA_REGISTRO,HORA_REGISTRO,ARCHIVO_REGISTRO);
     CLOSE C_INSERTAR_ARCHIVO;
     COMMIT;

     ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');

        ROLLBACK;

    END IF;

END VALIDACION_SEGURIDAD_INSERT_ARCHIVO;
--------------



END PCK_VALIDACION_ARCHIVO_COTIZACION_APP;
