create or replace NONEDITIONABLE PACKAGE PCK_VALIDACION_ARCHIVO_COTIZACION_APP AS 

PROCEDURE VALIDACION_SEGURIDAD_INSERT_ARCHIVO(NOMBRE_REGISTRO VARCHAR2,FECHA_REGISTRO VARCHAR2, HORA_REGISTRO VARCHAR2,ARCHIVO_REGISTRO VARCHAR2);



  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PCK_VALIDACION_ARCHIVO_COTIZACION_APP;