create or replace NONEDITIONABLE PACKAGE BODY PCK_VALIDACION_PROCESO_APP
AS


PROCEDURE VALIDACION_SEGURIDAD_INSERT_LOGIN(ID_REGISTRO NUMBER,EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,FECHA_LOGIN_REGISTRO VARCHAR2, HORA_LOGIN_REGISTRO VARCHAR2)
AS

 
 CURSOR C_INSERTAR_LOGIN 
 IS SELECT VALIDACION_LOGIN_EMAIL(EMAIL_REGISTRO), VALIDACION_LOGIN_CLAVE(CLAVE_REGISTRO) FROM LOGIN
 WHERE EMAIL=EMAIL_REGISTRO
 AND CLAVE=CLAVE_REGISTRO;

 CUR_INSERT_LOGIN C_INSERTAR_LOGIN%ROWTYPE;


BEGIN

    IF EMAIL_REGISTRO IS NOT NULL AND CLAVE_REGISTRO IS NOT NULL THEN

     OPEN C_INSERTAR_LOGIN;
     FETCH C_INSERTAR_LOGIN INTO CUR_INSERT_LOGIN;

     INSERT INTO LOGIN 
     VALUES (ID_REGISTRO,EMAIL_REGISTRO,CLAVE_REGISTRO,FECHA_LOGIN_REGISTRO,HORA_LOGIN_REGISTRO);
     CLOSE C_INSERTAR_LOGIN;
     COMMIT;

     ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');

        ROLLBACK;

    END IF;

END VALIDACION_SEGURIDAD_INSERT_LOGIN;

----------
PROCEDURE VALIDACION_SEGURIDAD_INSERT_SIGNUP(EMAIL_REGISTRO VARCHAR2,CLAVE_REGISTRO VARCHAR2,CLAVE VARCHAR,FECHA VARCHAR,NOMBRE VARCHAR,APELLIDO VARCHAR2,HORA_REGISTRO VARCHAR2)

AS

 
 CURSOR C_INSERTAR_SIGNUP
 IS SELECT  VALIDACION_LOGIN_EMAIL(EMAIL_REGISTRO), VALIDACION_LOGIN_CLAVE(CLAVE_REGISTRO) FROM SIGNUP
 WHERE EMAIL=EMAIL_REGISTRO
 AND CLAVE=CLAVE_REGISTRO;

 CUR_INSERT_SIGNUP C_INSERTAR_SIGNUP%ROWTYPE;


BEGIN

    IF EMAIL_REGISTRO IS NOT NULL AND CLAVE_REGISTRO IS NOT NULL THEN
    
     OPEN C_INSERTAR_SIGNUP;
     FETCH C_INSERTAR_SIGNUP INTO CUR_INSERT_SIGNUP;
    
     INSERT INTO SIGNUP 
     VALUES (EMAIL_REGISTRO,CLAVE_REGISTRO,CLAVE,FECHA,NOMBRE,APELLIDO,HORA_REGISTRO);
     CLOSE C_INSERTAR_SIGNUP;
     COMMIT;
     
    ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');
        ROLLBACK;

    END IF;
    
END VALIDACION_SEGURIDAD_INSERT_SIGNUP;
--------------



END PCK_VALIDACION_PROCESO_APP;

