create or replace NONEDITIONABLE PACKAGE BODY PCK_VALIDACION_CRUD_ARCHIVO_COTIZACION_APP
AS


PROCEDURE VALIDACION_SEGURIDAD_INSERT_CRUD_ARCHIVO(NOMBRE VARCHAR2,EMAIL VARCHAR2,DIRECCION VARCHAR2,SISTEMA_DESCRIPCION VARCHAR2,FECHA VARCHAR2,ARCHIVO VARCHAR2,ESTADO VARCHAR2,HORA VARCHAR)
AS
 
 CURSOR C_INSERTAR_CRUD
 IS SELECT * FROM CRUD_ARCHIVO_COTIZACION;

 CUR_INSERT__CRUD C_INSERTAR_CRUD%ROWTYPE;


BEGIN

    IF NOMBRE IS NOT NULL AND ARCHIVO = '.XLSX' || '.PDF' || '.CSV' THEN

     OPEN C_INSERTAR_CRUD;
     FETCH C_INSERTAR_CRUD INTO CUR_INSERT__CRUD;

     INSERT INTO CRUD_ARCHIVO_COTIZACION
     VALUES (NOMBRE,EMAIL,DIRECCION,SISTEMA_DESCRIPCION,FECHA,ARCHIVO,ESTADO,HORA);
     CLOSE C_INSERTAR_CRUD;
     COMMIT;

     ELSE
        DBMS_OUTPUT.PUT_LINE('ERROR');

        ROLLBACK;

    END IF;

END VALIDACION_SEGURIDAD_INSERT_CRUD_ARCHIVO;



END PCK_VALIDACION_CRUD_ARCHIVO_COTIZACION_APP;
