create or replace NONEDITIONABLE PACKAGE PCK_VALIDACION_CRUD_ARCHIVO_COTIZACION_APP AS 

PROCEDURE VALIDACION_SEGURIDAD_INSERT_CRUD_ARCHIVO(NOMBRE VARCHAR2,EMAIL VARCHAR2,DIRECCION VARCHAR2,SISTEMA_DESCRIPCION VARCHAR2,FECHA VARCHAR2,ARCHIVO VARCHAR2,ESTADO VARCHAR2,HORA VARCHAR);



  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

END PCK_VALIDACION_CRUD_ARCHIVO_COTIZACION_APP;